# Generated by Django 5.1.5 on 2025-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_author_alter_recipe_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes/covers/%Y/%m/%d"
            ),
        ),
    ]
