# Generated by Django 5.1.5 on 2025-02-06 22:13

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                blank=True,
                default=pathlib.PureWindowsPath(
                    "C:/Users/Miguel/OneDrive/Documentos/Curso_Django/projeto1/recipes/static/recipes/images/default_image.png"
                ),
                upload_to="recipes/covers/%Y/%m/%d",
            ),
        ),
    ]
