# Generated by Django 5.1.5 on 2025-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="default_images/default_image.png",
                upload_to="recipes/covers/%Y/%m/%d",
            ),
        ),
    ]
